-- Advanced Redirector - Supabase/Postgres schema + RPC + RLS

create table if not exists public.redirect_rules (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  target_url text not null,
  status_code integer not null default 302 check (status_code in (301, 302)),
  is_active boolean not null default true,
  pixel_enabled boolean not null default false,
  pixel_type text check (pixel_type in ('meta', 'tiktok', 'google', 'postback')),
  pixel_config jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint redirect_rules_slug_format check (slug ~ '^[a-z0-9][a-z0-9_-]{0,119}$'),
  constraint redirect_rules_pixel_consistency check (
    (pixel_enabled = false and pixel_type is null and pixel_config is null)
    or (pixel_enabled = true and pixel_type is not null and pixel_config is not null)
  )
);

create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  rule_id bigint references public.redirect_rules(id) on delete set null,
  slug text not null,
  target_url text not null,
  status_code integer not null check (status_code in (301, 302)),
  ip_hash text not null,
  user_agent text,
  referer text,
  referer_domain text not null default 'direct',
  country text not null default 'UNK',
  device_type text not null default 'unknown' check (device_type in ('mobile', 'desktop', 'bot', 'unknown')),
  query_string text not null default ''
);

create table if not exists public.pixel_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  rule_id bigint references public.redirect_rules(id) on delete set null,
  slug text not null,
  pixel_type text not null check (pixel_type in ('meta', 'tiktok', 'google', 'postback')),
  event_name text not null,
  status text not null check (status in ('success', 'error')),
  response_code integer,
  response_body text,
  error_message text,
  payload jsonb
);

create index if not exists idx_redirect_rules_active_slug on public.redirect_rules(slug) where is_active = true;
create index if not exists idx_logs_created_at on public.logs(created_at desc);
create index if not exists idx_logs_slug on public.logs(slug);
create index if not exists idx_logs_country on public.logs(country);
create index if not exists idx_logs_device_type on public.logs(device_type);
create index if not exists idx_logs_referer_domain on public.logs(referer_domain);
create index if not exists idx_pixel_logs_created_at on public.pixel_logs(created_at desc);
create index if not exists idx_pixel_logs_rule_id on public.pixel_logs(rule_id);
create index if not exists idx_pixel_logs_slug on public.pixel_logs(slug);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_redirect_rules_set_updated_at on public.redirect_rules;
create trigger trg_redirect_rules_set_updated_at
before update on public.redirect_rules
for each row
execute function public.set_updated_at();

alter table public.redirect_rules enable row level security;
alter table public.logs enable row level security;
alter table public.pixel_logs enable row level security;

drop policy if exists redirect_rules_service_role on public.redirect_rules;
create policy redirect_rules_service_role
on public.redirect_rules
for all
to service_role
using (true)
with check (true);

drop policy if exists redirect_rules_deny_anon on public.redirect_rules;
create policy redirect_rules_deny_anon
on public.redirect_rules
for all
to anon
using (false)
with check (false);

drop policy if exists redirect_rules_deny_authenticated on public.redirect_rules;
create policy redirect_rules_deny_authenticated
on public.redirect_rules
for all
to authenticated
using (false)
with check (false);

drop policy if exists logs_service_role on public.logs;
create policy logs_service_role
on public.logs
for all
to service_role
using (true)
with check (true);

drop policy if exists logs_deny_anon on public.logs;
create policy logs_deny_anon
on public.logs
for all
to anon
using (false)
with check (false);

drop policy if exists logs_deny_authenticated on public.logs;
create policy logs_deny_authenticated
on public.logs
for all
to authenticated
using (false)
with check (false);

drop policy if exists pixel_logs_service_role on public.pixel_logs;
create policy pixel_logs_service_role
on public.pixel_logs
for all
to service_role
using (true)
with check (true);

drop policy if exists pixel_logs_deny_anon on public.pixel_logs;
create policy pixel_logs_deny_anon
on public.pixel_logs
for all
to anon
using (false)
with check (false);

drop policy if exists pixel_logs_deny_authenticated on public.pixel_logs;
create policy pixel_logs_deny_authenticated
on public.pixel_logs
for all
to authenticated
using (false)
with check (false);

create or replace function public.resolve_redirect(
  p_slug text,
  p_default_url text,
  p_default_status integer,
  p_user_agent text,
  p_referer text,
  p_ip_hash text,
  p_country text,
  p_query_string text
)
returns table (
  resolved_slug text,
  target_url text,
  status_code integer,
  pixel_enabled boolean,
  pixel_type text,
  pixel_config jsonb,
  rule_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slug text;
  v_target_url text;
  v_status_code integer;
  v_pixel_enabled boolean := false;
  v_pixel_type text := null;
  v_pixel_config jsonb := null;
  v_rule_id bigint := null;
  v_referer_domain text := 'direct';
  v_device_type text := 'unknown';
begin
  v_slug := lower(btrim(coalesce(p_slug, '')));
  if v_slug = '' then
    v_slug := '/';
  end if;

  if v_slug <> '/' then
    select
      rr.id,
      rr.target_url,
      rr.status_code,
      rr.pixel_enabled,
      rr.pixel_type,
      rr.pixel_config
    into
      v_rule_id,
      v_target_url,
      v_status_code,
      v_pixel_enabled,
      v_pixel_type,
      v_pixel_config
    from public.redirect_rules rr
    where rr.slug = v_slug
      and rr.is_active = true
    order by rr.id desc
    limit 1;
  end if;

  if v_rule_id is null then
    v_target_url := p_default_url;
    v_status_code := case when p_default_status in (301, 302) then p_default_status else 302 end;
    v_pixel_enabled := false;
    v_pixel_type := null;
    v_pixel_config := null;
  end if;

  if coalesce(p_referer, '') <> '' then
    v_referer_domain := lower(split_part(split_part(split_part(p_referer, '://', 2), '/', 1), '?', 1));
    if coalesce(v_referer_domain, '') = '' then
      v_referer_domain := 'direct';
    end if;
  end if;

  if coalesce(p_user_agent, '') ~* '(bot|crawler|spider|crawling|headless|preview)' then
    v_device_type := 'bot';
  elsif coalesce(p_user_agent, '') ~* '(android|iphone|ipad|ipod|mobile|windows phone)' then
    v_device_type := 'mobile';
  elsif coalesce(p_user_agent, '') = '' then
    v_device_type := 'unknown';
  else
    v_device_type := 'desktop';
  end if;

  insert into public.logs (
    rule_id,
    slug,
    target_url,
    status_code,
    ip_hash,
    user_agent,
    referer,
    referer_domain,
    country,
    device_type,
    query_string
  ) values (
    v_rule_id,
    v_slug,
    v_target_url,
    v_status_code,
    p_ip_hash,
    nullif(p_user_agent, ''),
    nullif(p_referer, ''),
    v_referer_domain,
    coalesce(nullif(upper(p_country), ''), 'UNK'),
    v_device_type,
    coalesce(p_query_string, '')
  );

  return query
  select
    v_slug,
    v_target_url,
    v_status_code,
    v_pixel_enabled,
    v_pixel_type,
    v_pixel_config,
    v_rule_id;
end;
$$;

create or replace function public.stats_total_clicks()
returns table (total_clicks bigint)
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint as total_clicks
  from public.logs;
$$;

create or replace function public.stats_clicks_by_slug(p_limit integer default 100)
returns table (label text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  select
    l.slug::text as label,
    count(*)::bigint as clicks
  from public.logs l
  group by l.slug
  order by clicks desc, label asc
  limit greatest(coalesce(p_limit, 100), 1);
$$;

create or replace function public.stats_daily(p_days integer default 30)
returns table (day text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  with bounds as (
    select greatest(coalesce(p_days, 30), 1) as days
  ),
  series as (
    select generate_series(
      current_date - ((select days from bounds) - 1),
      current_date,
      interval '1 day'
    )::date as day
  ),
  agg as (
    select
      date_trunc('day', l.created_at)::date as day,
      count(*)::bigint as clicks
    from public.logs l
    where l.created_at >= (current_date - ((select days from bounds) - 1))::timestamp
    group by 1
  )
  select
    to_char(s.day, 'YYYY-MM-DD') as day,
    coalesce(a.clicks, 0)::bigint as clicks
  from series s
  left join agg a on a.day = s.day
  order by s.day asc;
$$;

create or replace function public.stats_hourly(p_days integer default 30)
returns table (hour text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  with bounds as (
    select greatest(coalesce(p_days, 30), 1) as days
  ),
  hours as (
    select generate_series(0, 23) as hour_num
  ),
  agg as (
    select
      extract(hour from l.created_at)::integer as hour_num,
      count(*)::bigint as clicks
    from public.logs l
    where l.created_at >= now() - make_interval(days => (select days from bounds))
    group by 1
  )
  select
    lpad(h.hour_num::text, 2, '0') as hour,
    coalesce(a.clicks, 0)::bigint as clicks
  from hours h
  left join agg a on a.hour_num = h.hour_num
  order by h.hour_num asc;
$$;

create or replace function public.stats_top_referrers(p_limit integer default 10)
returns table (label text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  select
    coalesce(nullif(l.referer_domain, ''), 'direct') as label,
    count(*)::bigint as clicks
  from public.logs l
  group by label
  order by clicks desc, label asc
  limit greatest(coalesce(p_limit, 10), 1);
$$;

create or replace function public.stats_top_devices(p_limit integer default 10)
returns table (label text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  select
    coalesce(nullif(l.device_type, ''), 'unknown') as label,
    count(*)::bigint as clicks
  from public.logs l
  group by label
  order by clicks desc, label asc
  limit greatest(coalesce(p_limit, 10), 1);
$$;

create or replace function public.stats_top_countries(p_limit integer default 10)
returns table (label text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  select
    coalesce(nullif(l.country, ''), 'UNK') as label,
    count(*)::bigint as clicks
  from public.logs l
  group by label
  order by clicks desc, label asc
  limit greatest(coalesce(p_limit, 10), 1);
$$;

revoke all on function public.resolve_redirect(text, text, integer, text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.resolve_redirect(text, text, integer, text, text, text, text, text) to service_role;

revoke all on function public.stats_total_clicks() from public, anon, authenticated;
grant execute on function public.stats_total_clicks() to service_role;

revoke all on function public.stats_clicks_by_slug(integer) from public, anon, authenticated;
grant execute on function public.stats_clicks_by_slug(integer) to service_role;

revoke all on function public.stats_daily(integer) from public, anon, authenticated;
grant execute on function public.stats_daily(integer) to service_role;

revoke all on function public.stats_hourly(integer) from public, anon, authenticated;
grant execute on function public.stats_hourly(integer) to service_role;

revoke all on function public.stats_top_referrers(integer) from public, anon, authenticated;
grant execute on function public.stats_top_referrers(integer) to service_role;

revoke all on function public.stats_top_devices(integer) from public, anon, authenticated;
grant execute on function public.stats_top_devices(integer) to service_role;

revoke all on function public.stats_top_countries(integer) from public, anon, authenticated;
grant execute on function public.stats_top_countries(integer) to service_role;

insert into public.redirect_rules (
  slug,
  target_url,
  status_code,
  is_active,
  pixel_enabled,
  pixel_type,
  pixel_config
)
values
  (
    'promo',
    'https://example.com/promo?src=redirect',
    302,
    true,
    true,
    'meta',
    '{"id":"META_PIXEL_ID","token":"META_ACCESS_TOKEN","event_name":"PageView","custom_params":{"campaign":"spring"}}'::jsonb
  ),
  (
    'docs',
    'https://example.com/docs',
    301,
    true,
    false,
    null,
    null
  ),
  (
    'partner',
    'https://partner.example.com/offer',
    302,
    true,
    true,
    'postback',
    '{"id":"https://webhook.site/your-endpoint","token":"","event_name":"click","custom_params":{"source":"redirector"}}'::jsonb
  )
on conflict (slug) do nothing;

-- Rebrandly-like links + click tracking (additive migration)
create extension if not exists pgcrypto;

create table if not exists public.short_links (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  destination_url text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid,
  title text,
  is_favorite boolean not null default false,
  tags text[] not null default '{}'::text[],
  redirect_type integer not null default 302 check (redirect_type in (301, 302)),
  routing_rules jsonb not null default '[]'::jsonb,
  deep_links jsonb not null default '{}'::jsonb,
  retargeting_scripts jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  constraint short_links_slug_format check (slug ~ '^[a-z0-9][a-z0-9_-]{0,119}$')
);

create table if not exists public.click_events (
  id uuid primary key default gen_random_uuid(),
  link_id uuid references public.short_links(id) on delete cascade,
  slug text not null,
  created_at timestamptz not null default now(),
  referrer text,
  ua text,
  ip_hash text not null,
  country text not null default 'UNK',
  region text,
  city text,
  device text not null default 'unknown',
  os text not null default 'unknown',
  browser text not null default 'unknown',
  platform text not null default 'unknown',
  language text not null default 'unknown',
  query_params jsonb not null default '{}'::jsonb,
  is_unique boolean not null default true,
  source text not null default 'direct',
  utm jsonb not null default '{}'::jsonb
);

create table if not exists public.admin_settings (
  id integer primary key default 1,
  plan text not null default 'free' check (plan in ('free', 'pro')),
  click_limit_monthly integer not null default 10000 check (click_limit_monthly > 0),
  tracking_enabled boolean not null default true,
  limit_behavior text not null default 'drop' check (limit_behavior in ('drop', 'minimal')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_settings_singleton check (id = 1)
);

create index if not exists idx_short_links_created_at on public.short_links(created_at desc);
create index if not exists idx_short_links_slug_active on public.short_links(slug) where is_active = true;
create index if not exists idx_short_links_favorite on public.short_links(is_favorite);
create index if not exists idx_click_events_link_created on public.click_events(link_id, created_at desc);
create index if not exists idx_click_events_slug on public.click_events(slug);
create index if not exists idx_click_events_created_at on public.click_events(created_at desc);
create index if not exists idx_click_events_ip_hash on public.click_events(ip_hash);
create index if not exists idx_click_events_source on public.click_events(source);
create index if not exists idx_click_events_country on public.click_events(country);
create index if not exists idx_click_events_browser on public.click_events(browser);
create index if not exists idx_click_events_device on public.click_events(device);

drop trigger if exists trg_short_links_set_updated_at on public.short_links;
create trigger trg_short_links_set_updated_at
before update on public.short_links
for each row
execute function public.set_updated_at();

drop trigger if exists trg_admin_settings_set_updated_at on public.admin_settings;
create trigger trg_admin_settings_set_updated_at
before update on public.admin_settings
for each row
execute function public.set_updated_at();

alter table public.short_links enable row level security;
alter table public.click_events enable row level security;
alter table public.admin_settings enable row level security;

drop policy if exists short_links_service_role on public.short_links;
create policy short_links_service_role
on public.short_links
for all
to service_role
using (true)
with check (true);

drop policy if exists short_links_deny_anon on public.short_links;
create policy short_links_deny_anon
on public.short_links
for all
to anon
using (false)
with check (false);

drop policy if exists short_links_deny_authenticated on public.short_links;
create policy short_links_deny_authenticated
on public.short_links
for all
to authenticated
using (false)
with check (false);

drop policy if exists click_events_service_role on public.click_events;
create policy click_events_service_role
on public.click_events
for all
to service_role
using (true)
with check (true);

drop policy if exists click_events_deny_anon on public.click_events;
create policy click_events_deny_anon
on public.click_events
for all
to anon
using (false)
with check (false);

drop policy if exists click_events_deny_authenticated on public.click_events;
create policy click_events_deny_authenticated
on public.click_events
for all
to authenticated
using (false)
with check (false);

drop policy if exists admin_settings_service_role on public.admin_settings;
create policy admin_settings_service_role
on public.admin_settings
for all
to service_role
using (true)
with check (true);

drop policy if exists admin_settings_deny_anon on public.admin_settings;
create policy admin_settings_deny_anon
on public.admin_settings
for all
to anon
using (false)
with check (false);

drop policy if exists admin_settings_deny_authenticated on public.admin_settings;
create policy admin_settings_deny_authenticated
on public.admin_settings
for all
to authenticated
using (false)
with check (false);

create or replace function public.get_admin_settings()
returns table (
  plan text,
  click_limit_monthly integer,
  tracking_enabled boolean,
  limit_behavior text
)
language sql
security definer
set search_path = public
as $$
  with settings as (
    select s.plan, s.click_limit_monthly, s.tracking_enabled, s.limit_behavior
    from public.admin_settings s
    order by s.id asc
    limit 1
  )
  select
    coalesce((select plan from settings), 'free')::text as plan,
    coalesce((select click_limit_monthly from settings), 10000)::integer as click_limit_monthly,
    coalesce((select tracking_enabled from settings), true)::boolean as tracking_enabled,
    coalesce((select limit_behavior from settings), 'drop')::text as limit_behavior;
$$;

create or replace function public.current_month_clicks()
returns table (total_clicks bigint)
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint as total_clicks
  from public.click_events ce
  where ce.created_at >= date_trunc('month', now())
    and ce.created_at < (date_trunc('month', now()) + interval '1 month');
$$;

create or replace function public.list_short_links_with_stats(p_limit integer default 25, p_offset integer default 0)
returns table (
  id uuid,
  slug text,
  destination_url text,
  created_at timestamptz,
  is_favorite boolean,
  tags text[],
  redirect_type integer,
  clicks_received bigint,
  clicks_today bigint,
  last_click_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  with bounds as (
    select greatest(coalesce(p_limit, 25), 1) as page_limit, greatest(coalesce(p_offset, 0), 0) as page_offset
  ),
  paged as (
    select
      sl.id,
      sl.slug,
      sl.destination_url,
      sl.created_at,
      sl.is_favorite,
      sl.tags,
      sl.redirect_type
    from public.short_links sl
    where sl.is_active = true
    order by sl.created_at desc
    limit (select page_limit from bounds)
    offset (select page_offset from bounds)
  ),
  aggregated as (
    select
      ce.link_id,
      count(*)::bigint as clicks_received,
      count(*) filter (where ce.created_at >= date_trunc('day', now()))::bigint as clicks_today,
      max(ce.created_at) as last_click_at
    from public.click_events ce
    where ce.link_id in (select p.id from paged p)
    group by ce.link_id
  )
  select
    p.id,
    p.slug,
    p.destination_url,
    p.created_at,
    p.is_favorite,
    p.tags,
    p.redirect_type,
    coalesce(a.clicks_received, 0)::bigint as clicks_received,
    coalesce(a.clicks_today, 0)::bigint as clicks_today,
    a.last_click_at
  from paged p
  left join aggregated a on a.link_id = p.id
  order by p.created_at desc;
$$;

create or replace function public.get_link_overview(p_link_id uuid)
returns table (
  total_clicks bigint,
  qr_scans bigint,
  clicks_today bigint,
  last_click_at timestamptz,
  unique_clicks bigint,
  non_unique_clicks bigint
)
language sql
security definer
set search_path = public
as $$
  select
    count(*)::bigint as total_clicks,
    0::bigint as qr_scans,
    count(*) filter (where ce.created_at >= date_trunc('day', now()))::bigint as clicks_today,
    max(ce.created_at) as last_click_at,
    count(*) filter (where ce.is_unique = true)::bigint as unique_clicks,
    count(*) filter (where ce.is_unique = false)::bigint as non_unique_clicks
  from public.click_events ce
  where ce.link_id = p_link_id;
$$;

create or replace function public.get_link_timeseries(
  p_link_id uuid,
  p_granularity text default 'days',
  p_points integer default 30
)
returns table (
  bucket_at timestamptz,
  label text,
  clicks bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_granularity text := lower(coalesce(p_granularity, 'days'));
  v_points integer := greatest(coalesce(p_points, 30), 1);
  v_start timestamptz;
  v_end timestamptz;
  v_step interval;
  v_label_format text;
  v_trunc text;
begin
  if v_granularity = 'hours' then
    v_trunc := 'hour';
    v_step := interval '1 hour';
    v_end := date_trunc('hour', now());
    v_start := v_end - make_interval(hours => (v_points - 1));
    v_label_format := 'HH24:00';
  elsif v_granularity = 'months' then
    v_trunc := 'month';
    v_step := interval '1 month';
    v_end := date_trunc('month', now());
    v_start := v_end - make_interval(months => (v_points - 1));
    v_label_format := 'YYYY-MM';
  else
    v_trunc := 'day';
    v_step := interval '1 day';
    v_end := date_trunc('day', now());
    v_start := v_end - make_interval(days => (v_points - 1));
    v_label_format := 'MM-DD';
  end if;

  return query
  with series as (
    select generate_series(v_start, v_end, v_step) as bucket
  ),
  agg as (
    select
      date_trunc(v_trunc, ce.created_at) as bucket,
      count(*)::bigint as clicks
    from public.click_events ce
    where ce.link_id = p_link_id
      and ce.created_at >= v_start
      and ce.created_at < (v_end + v_step)
    group by 1
  )
  select
    s.bucket::timestamptz as bucket_at,
    to_char(s.bucket, v_label_format) as label,
    coalesce(a.clicks, 0)::bigint as clicks
  from series s
  left join agg a on a.bucket = s.bucket
  order by s.bucket asc;
end;
$$;

create or replace function public.get_link_top_dimension(
  p_link_id uuid,
  p_dimension text,
  p_limit integer default 10
)
returns table (
  label text,
  clicks bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_dimension text := lower(coalesce(p_dimension, ''));
  v_limit integer := greatest(coalesce(p_limit, 10), 1);
begin
  return query
  select
    case v_dimension
      when 'country' then coalesce(nullif(upper(ce.country), ''), 'UNK')
      when 'region' then coalesce(nullif(ce.region, ''), 'unknown')
      when 'city' then coalesce(nullif(ce.city, ''), 'unknown')
      when 'source' then coalesce(nullif(ce.source, ''), 'direct')
      when 'browser' then coalesce(nullif(ce.browser, ''), 'unknown')
      when 'device' then coalesce(nullif(ce.device, ''), 'unknown')
      when 'os' then coalesce(nullif(ce.os, ''), 'unknown')
      when 'language' then coalesce(nullif(ce.language, ''), 'unknown')
      when 'platform' then coalesce(nullif(ce.platform, ''), 'unknown')
      when 'social' then
        case
          when lower(coalesce(ce.source, '')) in ('facebook', 'instagram', 'tiktok', 'twitter', 'x', 'linkedin', 'youtube', 'reddit', 'snapchat', 'pinterest')
            then lower(ce.source)
          else 'other'
        end
      else 'unknown'
    end as label,
    count(*)::bigint as clicks
  from public.click_events ce
  where ce.link_id = p_link_id
  group by 1
  order by clicks desc, label asc
  limit v_limit;
end;
$$;

create or replace function public.get_link_day_breakdown(p_link_id uuid)
returns table (
  label text,
  clicks bigint
)
language sql
security definer
set search_path = public
as $$
  with days as (
    select * from (values
      (0, 'Sun'),
      (1, 'Mon'),
      (2, 'Tue'),
      (3, 'Wed'),
      (4, 'Thu'),
      (5, 'Fri'),
      (6, 'Sat')
    ) as d(dow, label)
  ),
  agg as (
    select
      extract(dow from ce.created_at)::integer as dow,
      count(*)::bigint as clicks
    from public.click_events ce
    where ce.link_id = p_link_id
    group by 1
  )
  select
    d.label,
    coalesce(a.clicks, 0)::bigint as clicks
  from days d
  left join agg a on a.dow = d.dow
  order by d.dow asc;
$$;

create or replace function public.get_link_hour_breakdown(p_link_id uuid)
returns table (
  label text,
  clicks bigint
)
language sql
security definer
set search_path = public
as $$
  with hours as (
    select generate_series(0, 23) as hour_num
  ),
  agg as (
    select
      extract(hour from ce.created_at)::integer as hour_num,
      count(*)::bigint as clicks
    from public.click_events ce
    where ce.link_id = p_link_id
    group by 1
  )
  select
    lpad(h.hour_num::text, 2, '0') || ':00' as label,
    coalesce(a.clicks, 0)::bigint as clicks
  from hours h
  left join agg a on a.hour_num = h.hour_num
  order by h.hour_num asc;
$$;

revoke all on function public.get_admin_settings() from public, anon, authenticated;
grant execute on function public.get_admin_settings() to service_role;

revoke all on function public.current_month_clicks() from public, anon, authenticated;
grant execute on function public.current_month_clicks() to service_role;

revoke all on function public.list_short_links_with_stats(integer, integer) from public, anon, authenticated;
grant execute on function public.list_short_links_with_stats(integer, integer) to service_role;

revoke all on function public.get_link_overview(uuid) from public, anon, authenticated;
grant execute on function public.get_link_overview(uuid) to service_role;

revoke all on function public.get_link_timeseries(uuid, text, integer) from public, anon, authenticated;
grant execute on function public.get_link_timeseries(uuid, text, integer) to service_role;

revoke all on function public.get_link_top_dimension(uuid, text, integer) from public, anon, authenticated;
grant execute on function public.get_link_top_dimension(uuid, text, integer) to service_role;

revoke all on function public.get_link_day_breakdown(uuid) from public, anon, authenticated;
grant execute on function public.get_link_day_breakdown(uuid) to service_role;

revoke all on function public.get_link_hour_breakdown(uuid) from public, anon, authenticated;
grant execute on function public.get_link_hour_breakdown(uuid) to service_role;

insert into public.admin_settings (id, plan, click_limit_monthly, tracking_enabled, limit_behavior)
values (1, 'free', 10000, true, 'drop')
on conflict (id) do nothing;

insert into public.short_links (slug, destination_url, redirect_type, tags, is_active)
select
  rr.slug,
  rr.target_url,
  rr.status_code,
  '{}'::text[],
  rr.is_active
from public.redirect_rules rr
on conflict (slug) do nothing;

-- 2026-03 tracking hardening + optional TikTok landing
alter table if exists public.admin_settings
  add column if not exists landing_enabled boolean not null default false,
  add column if not exists global_background_url text;

alter table if exists public.short_links
  add column if not exists landing_mode text not null default 'inherit',
  add column if not exists background_url text;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'short_links_landing_mode_check'
  ) then
    alter table public.short_links
      add constraint short_links_landing_mode_check check (landing_mode in ('inherit', 'on', 'off'));
  end if;
end;
$$;

alter table if exists public.click_events
  add column if not exists event_type text not null default 'redirect',
  add column if not exists traffic_category text not null default 'unknown',
  add column if not exists request_method text not null default 'GET',
  add column if not exists is_bot boolean not null default false,
  add column if not exists is_prefetch boolean not null default false,
  add column if not exists dedup_key text,
  add column if not exists request_headers jsonb not null default '{}'::jsonb,
  add column if not exists metadata jsonb not null default '{}'::jsonb;

update public.click_events
set event_type = 'redirect'
where event_type is null or btrim(event_type) = '';

update public.click_events
set traffic_category = case
  when coalesce(device, '') = 'bot' then 'bot'
  else 'unknown'
end
where traffic_category is null or btrim(traffic_category) = '';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'click_events_event_type_check'
  ) then
    alter table public.click_events
      add constraint click_events_event_type_check check (event_type in ('visit', 'landing_view', 'human_click', 'redirect'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'click_events_traffic_category_check'
  ) then
    alter table public.click_events
      add constraint click_events_traffic_category_check check (traffic_category in ('human', 'bot', 'prefetch', 'unknown'));
  end if;
end;
$$;

create index if not exists idx_click_events_event_type on public.click_events(event_type);
create index if not exists idx_click_events_traffic_category on public.click_events(traffic_category);
create index if not exists idx_click_events_method on public.click_events(request_method);
with ranked as (
  select
    ce.id,
    row_number() over (partition by ce.event_type, ce.dedup_key order by ce.created_at asc, ce.id asc) as rn
  from public.click_events ce
  where ce.dedup_key is not null and btrim(ce.dedup_key) <> ''
)
delete from public.click_events ce
using ranked r
where ce.id = r.id
  and r.rn > 1;

drop index if exists public.idx_click_events_event_dedup;
create unique index if not exists idx_click_events_event_dedup
  on public.click_events(event_type, dedup_key);

drop function if exists public.get_admin_settings();
create or replace function public.get_admin_settings()
returns table (
  plan text,
  click_limit_monthly integer,
  tracking_enabled boolean,
  landing_enabled boolean,
  global_background_url text,
  limit_behavior text
)
language sql
security definer
set search_path = public
as $$
  with settings as (
    select
      s.plan,
      s.click_limit_monthly,
      s.tracking_enabled,
      s.landing_enabled,
      s.global_background_url,
      s.limit_behavior
    from public.admin_settings s
    order by s.id asc
    limit 1
  )
  select
    coalesce((select plan from settings), 'free')::text as plan,
    coalesce((select click_limit_monthly from settings), 10000)::integer as click_limit_monthly,
    coalesce((select tracking_enabled from settings), true)::boolean as tracking_enabled,
    coalesce((select landing_enabled from settings), false)::boolean as landing_enabled,
    nullif((select global_background_url from settings), '')::text as global_background_url,
    coalesce((select limit_behavior from settings), 'drop')::text as limit_behavior;
$$;

drop function if exists public.list_short_links_with_stats(integer, integer);
create or replace function public.list_short_links_with_stats(p_limit integer default 25, p_offset integer default 0)
returns table (
  id uuid,
  slug text,
  destination_url text,
  created_at timestamptz,
  is_favorite boolean,
  tags text[],
  redirect_type integer,
  clicks_received bigint,
  clicks_today bigint,
  last_click_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  with bounds as (
    select greatest(coalesce(p_limit, 25), 1) as page_limit, greatest(coalesce(p_offset, 0), 0) as page_offset
  ),
  paged as (
    select
      sl.id,
      sl.slug,
      sl.destination_url,
      sl.created_at,
      sl.is_favorite,
      sl.tags,
      sl.redirect_type
    from public.short_links sl
    where sl.is_active = true
    order by sl.created_at desc
    limit (select page_limit from bounds)
    offset (select page_offset from bounds)
  ),
  aggregated as (
    select
      ce.link_id,
      count(*) filter (
        where ce.event_type = 'redirect'
          and ce.traffic_category = 'human'
          and ce.request_method = 'GET'
      )::bigint as clicks_received,
      count(*) filter (
        where ce.event_type = 'redirect'
          and ce.traffic_category = 'human'
          and ce.request_method = 'GET'
          and ce.created_at >= date_trunc('day', now())
      )::bigint as clicks_today,
      max(ce.created_at) filter (
        where ce.event_type = 'redirect'
          and ce.traffic_category = 'human'
          and ce.request_method = 'GET'
      ) as last_click_at
    from public.click_events ce
    where ce.link_id in (select p.id from paged p)
    group by ce.link_id
  )
  select
    p.id,
    p.slug,
    p.destination_url,
    p.created_at,
    p.is_favorite,
    p.tags,
    p.redirect_type,
    coalesce(a.clicks_received, 0)::bigint as clicks_received,
    coalesce(a.clicks_today, 0)::bigint as clicks_today,
    a.last_click_at
  from paged p
  left join aggregated a on a.link_id = p.id
  order by p.created_at desc;
$$;

drop function if exists public.get_link_overview(uuid);
create or replace function public.get_link_overview(p_link_id uuid)
returns table (
  total_clicks bigint,
  qr_scans bigint,
  clicks_today bigint,
  last_click_at timestamptz,
  unique_clicks bigint,
  non_unique_clicks bigint,
  visits bigint,
  landing_views bigint,
  human_clicks bigint,
  redirects bigint,
  direct_redirects bigint,
  bot_hits bigint,
  prefetch_hits bigint
)
language sql
security definer
set search_path = public
as $$
  select
    count(*) filter (
      where ce.event_type = 'redirect'
        and ce.traffic_category = 'human'
        and ce.request_method = 'GET'
    )::bigint as total_clicks,
    0::bigint as qr_scans,
    count(*) filter (
      where ce.event_type = 'redirect'
        and ce.traffic_category = 'human'
        and ce.request_method = 'GET'
        and ce.created_at >= date_trunc('day', now())
    )::bigint as clicks_today,
    max(ce.created_at) filter (
      where ce.event_type = 'redirect'
        and ce.traffic_category = 'human'
        and ce.request_method = 'GET'
    ) as last_click_at,
    count(*) filter (
      where ce.event_type = 'redirect'
        and ce.traffic_category = 'human'
        and ce.request_method = 'GET'
        and ce.is_unique = true
    )::bigint as unique_clicks,
    count(*) filter (
      where ce.event_type = 'redirect'
        and ce.traffic_category = 'human'
        and ce.request_method = 'GET'
        and ce.is_unique = false
    )::bigint as non_unique_clicks,
    count(*) filter (where ce.event_type = 'visit')::bigint as visits,
    count(*) filter (where ce.event_type = 'landing_view')::bigint as landing_views,
    count(*) filter (where ce.event_type = 'human_click')::bigint as human_clicks,
    count(*) filter (
      where ce.event_type = 'redirect'
        and ce.traffic_category = 'human'
        and ce.request_method = 'GET'
    )::bigint as redirects,
    count(*) filter (
      where ce.event_type = 'redirect'
        and ce.traffic_category = 'human'
        and ce.request_method = 'GET'
        and coalesce(ce.metadata->>'redirect_path', '') = 'direct'
    )::bigint as direct_redirects,
    count(*) filter (where ce.traffic_category = 'bot')::bigint as bot_hits,
    count(*) filter (where ce.traffic_category = 'prefetch')::bigint as prefetch_hits
  from public.click_events ce
  where ce.link_id = p_link_id;
$$;

create or replace function public.current_month_clicks()
returns table (total_clicks bigint)
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint as total_clicks
  from public.click_events ce
  where ce.created_at >= date_trunc('month', now())
    and ce.created_at < (date_trunc('month', now()) + interval '1 month')
    and ce.event_type = 'redirect'
    and ce.traffic_category = 'human'
    and ce.request_method = 'GET';
$$;

create or replace function public.get_link_timeseries(
  p_link_id uuid,
  p_granularity text default 'days',
  p_points integer default 30
)
returns table (
  bucket_at timestamptz,
  label text,
  clicks bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_granularity text := lower(coalesce(p_granularity, 'days'));
  v_points integer := greatest(coalesce(p_points, 30), 1);
  v_start timestamptz;
  v_end timestamptz;
  v_step interval;
  v_label_format text;
  v_trunc text;
begin
  if v_granularity = 'hours' then
    v_trunc := 'hour';
    v_step := interval '1 hour';
    v_end := date_trunc('hour', now());
    v_start := v_end - make_interval(hours => (v_points - 1));
    v_label_format := 'HH24:00';
  elsif v_granularity = 'months' then
    v_trunc := 'month';
    v_step := interval '1 month';
    v_end := date_trunc('month', now());
    v_start := v_end - make_interval(months => (v_points - 1));
    v_label_format := 'YYYY-MM';
  else
    v_trunc := 'day';
    v_step := interval '1 day';
    v_end := date_trunc('day', now());
    v_start := v_end - make_interval(days => (v_points - 1));
    v_label_format := 'MM-DD';
  end if;

  return query
  with series as (
    select generate_series(v_start, v_end, v_step) as bucket
  ),
  agg as (
    select
      date_trunc(v_trunc, ce.created_at) as bucket,
      count(*)::bigint as clicks
    from public.click_events ce
    where ce.link_id = p_link_id
      and ce.created_at >= v_start
      and ce.created_at < (v_end + v_step)
      and ce.event_type = 'redirect'
      and ce.traffic_category = 'human'
      and ce.request_method = 'GET'
    group by 1
  )
  select
    s.bucket::timestamptz as bucket_at,
    to_char(s.bucket, v_label_format) as label,
    coalesce(a.clicks, 0)::bigint as clicks
  from series s
  left join agg a on a.bucket = s.bucket
  order by s.bucket asc;
end;
$$;

create or replace function public.get_link_top_dimension(
  p_link_id uuid,
  p_dimension text,
  p_limit integer default 10
)
returns table (
  label text,
  clicks bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_dimension text := lower(coalesce(p_dimension, ''));
  v_limit integer := greatest(coalesce(p_limit, 10), 1);
begin
  return query
  select
    case v_dimension
      when 'country' then coalesce(nullif(upper(ce.country), ''), 'UNK')
      when 'region' then coalesce(nullif(ce.region, ''), 'unknown')
      when 'city' then coalesce(nullif(ce.city, ''), 'unknown')
      when 'source' then coalesce(nullif(ce.source, ''), 'direct')
      when 'browser' then coalesce(nullif(ce.browser, ''), 'unknown')
      when 'device' then coalesce(nullif(ce.device, ''), 'unknown')
      when 'os' then coalesce(nullif(ce.os, ''), 'unknown')
      when 'language' then coalesce(nullif(ce.language, ''), 'unknown')
      when 'platform' then coalesce(nullif(ce.platform, ''), 'unknown')
      when 'social' then
        case
          when lower(coalesce(ce.source, '')) in ('facebook', 'instagram', 'tiktok', 'twitter', 'x', 'linkedin', 'youtube', 'reddit', 'snapchat', 'pinterest')
            then lower(ce.source)
          else 'other'
        end
      else 'unknown'
    end as label,
    count(*)::bigint as clicks
  from public.click_events ce
  where ce.link_id = p_link_id
    and ce.event_type = 'redirect'
    and ce.traffic_category = 'human'
    and ce.request_method = 'GET'
  group by 1
  order by clicks desc, label asc
  limit v_limit;
end;
$$;

create or replace function public.get_link_day_breakdown(p_link_id uuid)
returns table (
  label text,
  clicks bigint
)
language sql
security definer
set search_path = public
as $$
  with days as (
    select * from (values
      (0, 'Sun'),
      (1, 'Mon'),
      (2, 'Tue'),
      (3, 'Wed'),
      (4, 'Thu'),
      (5, 'Fri'),
      (6, 'Sat')
    ) as d(dow, label)
  ),
  agg as (
    select
      extract(dow from ce.created_at)::integer as dow,
      count(*)::bigint as clicks
    from public.click_events ce
    where ce.link_id = p_link_id
      and ce.event_type = 'redirect'
      and ce.traffic_category = 'human'
      and ce.request_method = 'GET'
    group by 1
  )
  select
    d.label,
    coalesce(a.clicks, 0)::bigint as clicks
  from days d
  left join agg a on a.dow = d.dow
  order by d.dow asc;
$$;

create or replace function public.get_link_hour_breakdown(p_link_id uuid)
returns table (
  label text,
  clicks bigint
)
language sql
security definer
set search_path = public
as $$
  with hours as (
    select generate_series(0, 23) as hour_num
  ),
  agg as (
    select
      extract(hour from ce.created_at)::integer as hour_num,
      count(*)::bigint as clicks
    from public.click_events ce
    where ce.link_id = p_link_id
      and ce.event_type = 'redirect'
      and ce.traffic_category = 'human'
      and ce.request_method = 'GET'
    group by 1
  )
  select
    lpad(h.hour_num::text, 2, '0') || ':00' as label,
    coalesce(a.clicks, 0)::bigint as clicks
  from hours h
  left join agg a on a.hour_num = h.hour_num
  order by h.hour_num asc;
$$;

revoke all on function public.get_admin_settings() from public, anon, authenticated;
grant execute on function public.get_admin_settings() to service_role;

revoke all on function public.list_short_links_with_stats(integer, integer) from public, anon, authenticated;
grant execute on function public.list_short_links_with_stats(integer, integer) to service_role;

revoke all on function public.get_link_overview(uuid) from public, anon, authenticated;
grant execute on function public.get_link_overview(uuid) to service_role;

revoke all on function public.current_month_clicks() from public, anon, authenticated;
grant execute on function public.current_month_clicks() to service_role;

revoke all on function public.get_link_timeseries(uuid, text, integer) from public, anon, authenticated;
grant execute on function public.get_link_timeseries(uuid, text, integer) to service_role;

revoke all on function public.get_link_top_dimension(uuid, text, integer) from public, anon, authenticated;
grant execute on function public.get_link_top_dimension(uuid, text, integer) to service_role;

revoke all on function public.get_link_day_breakdown(uuid) from public, anon, authenticated;
grant execute on function public.get_link_day_breakdown(uuid) to service_role;

revoke all on function public.get_link_hour_breakdown(uuid) from public, anon, authenticated;
grant execute on function public.get_link_hour_breakdown(uuid) to service_role;
