-- Advanced Redirector - Supabase/Postgres schema + RPC + RLS

create table if not exists public.redirect_rules (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  target_url text not null,
  status_code integer not null default 302 check (status_code in (301, 302)),
  is_active boolean not null default true,
  pixel_enabled boolean not null default false,
  pixel_type text check (pixel_type in ('meta', 'tiktok', 'google', 'postback')),
  pixel_config jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint redirect_rules_slug_format check (slug ~ '^[a-z0-9][a-z0-9_-]{0,119}$'),
  constraint redirect_rules_pixel_consistency check (
    (pixel_enabled = false and pixel_type is null and pixel_config is null)
    or (pixel_enabled = true and pixel_type is not null and pixel_config is not null)
  )
);

create table if not exists public.logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  rule_id bigint references public.redirect_rules(id) on delete set null,
  slug text not null,
  target_url text not null,
  status_code integer not null check (status_code in (301, 302)),
  ip_hash text not null,
  user_agent text,
  referer text,
  referer_domain text not null default 'direct',
  country text not null default 'UNK',
  device_type text not null default 'unknown' check (device_type in ('mobile', 'desktop', 'bot', 'unknown')),
  query_string text not null default ''
);

create table if not exists public.pixel_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  rule_id bigint references public.redirect_rules(id) on delete set null,
  slug text not null,
  pixel_type text not null check (pixel_type in ('meta', 'tiktok', 'google', 'postback')),
  event_name text not null,
  status text not null check (status in ('success', 'error')),
  response_code integer,
  response_body text,
  error_message text,
  payload jsonb
);

create index if not exists idx_redirect_rules_active_slug on public.redirect_rules(slug) where is_active = true;
create index if not exists idx_logs_created_at on public.logs(created_at desc);
create index if not exists idx_logs_slug on public.logs(slug);
create index if not exists idx_logs_country on public.logs(country);
create index if not exists idx_logs_device_type on public.logs(device_type);
create index if not exists idx_logs_referer_domain on public.logs(referer_domain);
create index if not exists idx_pixel_logs_created_at on public.pixel_logs(created_at desc);
create index if not exists idx_pixel_logs_rule_id on public.pixel_logs(rule_id);
create index if not exists idx_pixel_logs_slug on public.pixel_logs(slug);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_redirect_rules_set_updated_at on public.redirect_rules;
create trigger trg_redirect_rules_set_updated_at
before update on public.redirect_rules
for each row
execute function public.set_updated_at();

alter table public.redirect_rules enable row level security;
alter table public.logs enable row level security;
alter table public.pixel_logs enable row level security;

drop policy if exists redirect_rules_service_role on public.redirect_rules;
create policy redirect_rules_service_role
on public.redirect_rules
for all
to service_role
using (true)
with check (true);

drop policy if exists redirect_rules_deny_anon on public.redirect_rules;
create policy redirect_rules_deny_anon
on public.redirect_rules
for all
to anon
using (false)
with check (false);

drop policy if exists redirect_rules_deny_authenticated on public.redirect_rules;
create policy redirect_rules_deny_authenticated
on public.redirect_rules
for all
to authenticated
using (false)
with check (false);

drop policy if exists logs_service_role on public.logs;
create policy logs_service_role
on public.logs
for all
to service_role
using (true)
with check (true);

drop policy if exists logs_deny_anon on public.logs;
create policy logs_deny_anon
on public.logs
for all
to anon
using (false)
with check (false);

drop policy if exists logs_deny_authenticated on public.logs;
create policy logs_deny_authenticated
on public.logs
for all
to authenticated
using (false)
with check (false);

drop policy if exists pixel_logs_service_role on public.pixel_logs;
create policy pixel_logs_service_role
on public.pixel_logs
for all
to service_role
using (true)
with check (true);

drop policy if exists pixel_logs_deny_anon on public.pixel_logs;
create policy pixel_logs_deny_anon
on public.pixel_logs
for all
to anon
using (false)
with check (false);

drop policy if exists pixel_logs_deny_authenticated on public.pixel_logs;
create policy pixel_logs_deny_authenticated
on public.pixel_logs
for all
to authenticated
using (false)
with check (false);

create or replace function public.resolve_redirect(
  p_slug text,
  p_default_url text,
  p_default_status integer,
  p_user_agent text,
  p_referer text,
  p_ip_hash text,
  p_country text,
  p_query_string text
)
returns table (
  resolved_slug text,
  target_url text,
  status_code integer,
  pixel_enabled boolean,
  pixel_type text,
  pixel_config jsonb,
  rule_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slug text;
  v_target_url text;
  v_status_code integer;
  v_pixel_enabled boolean := false;
  v_pixel_type text := null;
  v_pixel_config jsonb := null;
  v_rule_id bigint := null;
  v_referer_domain text := 'direct';
  v_device_type text := 'unknown';
begin
  v_slug := lower(btrim(coalesce(p_slug, '')));
  if v_slug = '' then
    v_slug := '/';
  end if;

  if v_slug <> '/' then
    select
      rr.id,
      rr.target_url,
      rr.status_code,
      rr.pixel_enabled,
      rr.pixel_type,
      rr.pixel_config
    into
      v_rule_id,
      v_target_url,
      v_status_code,
      v_pixel_enabled,
      v_pixel_type,
      v_pixel_config
    from public.redirect_rules rr
    where rr.slug = v_slug
      and rr.is_active = true
    order by rr.id desc
    limit 1;
  end if;

  if v_rule_id is null then
    v_target_url := p_default_url;
    v_status_code := case when p_default_status in (301, 302) then p_default_status else 302 end;
    v_pixel_enabled := false;
    v_pixel_type := null;
    v_pixel_config := null;
  end if;

  if coalesce(p_referer, '') <> '' then
    v_referer_domain := lower(split_part(split_part(split_part(p_referer, '://', 2), '/', 1), '?', 1));
    if coalesce(v_referer_domain, '') = '' then
      v_referer_domain := 'direct';
    end if;
  end if;

  if coalesce(p_user_agent, '') ~* '(bot|crawler|spider|crawling|headless|preview)' then
    v_device_type := 'bot';
  elsif coalesce(p_user_agent, '') ~* '(android|iphone|ipad|ipod|mobile|windows phone)' then
    v_device_type := 'mobile';
  elsif coalesce(p_user_agent, '') = '' then
    v_device_type := 'unknown';
  else
    v_device_type := 'desktop';
  end if;

  insert into public.logs (
    rule_id,
    slug,
    target_url,
    status_code,
    ip_hash,
    user_agent,
    referer,
    referer_domain,
    country,
    device_type,
    query_string
  ) values (
    v_rule_id,
    v_slug,
    v_target_url,
    v_status_code,
    p_ip_hash,
    nullif(p_user_agent, ''),
    nullif(p_referer, ''),
    v_referer_domain,
    coalesce(nullif(upper(p_country), ''), 'UNK'),
    v_device_type,
    coalesce(p_query_string, '')
  );

  return query
  select
    v_slug,
    v_target_url,
    v_status_code,
    v_pixel_enabled,
    v_pixel_type,
    v_pixel_config,
    v_rule_id;
end;
$$;

create or replace function public.stats_total_clicks()
returns table (total_clicks bigint)
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint as total_clicks
  from public.logs;
$$;

create or replace function public.stats_clicks_by_slug(p_limit integer default 100)
returns table (label text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  select
    l.slug::text as label,
    count(*)::bigint as clicks
  from public.logs l
  group by l.slug
  order by clicks desc, label asc
  limit greatest(coalesce(p_limit, 100), 1);
$$;

create or replace function public.stats_daily(p_days integer default 30)
returns table (day text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  with bounds as (
    select greatest(coalesce(p_days, 30), 1) as days
  ),
  series as (
    select generate_series(
      current_date - ((select days from bounds) - 1),
      current_date,
      interval '1 day'
    )::date as day
  ),
  agg as (
    select
      date_trunc('day', l.created_at)::date as day,
      count(*)::bigint as clicks
    from public.logs l
    where l.created_at >= (current_date - ((select days from bounds) - 1))::timestamp
    group by 1
  )
  select
    to_char(s.day, 'YYYY-MM-DD') as day,
    coalesce(a.clicks, 0)::bigint as clicks
  from series s
  left join agg a on a.day = s.day
  order by s.day asc;
$$;

create or replace function public.stats_hourly(p_days integer default 30)
returns table (hour text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  with bounds as (
    select greatest(coalesce(p_days, 30), 1) as days
  ),
  hours as (
    select generate_series(0, 23) as hour_num
  ),
  agg as (
    select
      extract(hour from l.created_at)::integer as hour_num,
      count(*)::bigint as clicks
    from public.logs l
    where l.created_at >= now() - make_interval(days => (select days from bounds))
    group by 1
  )
  select
    lpad(h.hour_num::text, 2, '0') as hour,
    coalesce(a.clicks, 0)::bigint as clicks
  from hours h
  left join agg a on a.hour_num = h.hour_num
  order by h.hour_num asc;
$$;

create or replace function public.stats_top_referrers(p_limit integer default 10)
returns table (label text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  select
    coalesce(nullif(l.referer_domain, ''), 'direct') as label,
    count(*)::bigint as clicks
  from public.logs l
  group by label
  order by clicks desc, label asc
  limit greatest(coalesce(p_limit, 10), 1);
$$;

create or replace function public.stats_top_devices(p_limit integer default 10)
returns table (label text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  select
    coalesce(nullif(l.device_type, ''), 'unknown') as label,
    count(*)::bigint as clicks
  from public.logs l
  group by label
  order by clicks desc, label asc
  limit greatest(coalesce(p_limit, 10), 1);
$$;

create or replace function public.stats_top_countries(p_limit integer default 10)
returns table (label text, clicks bigint)
language sql
security definer
set search_path = public
as $$
  select
    coalesce(nullif(l.country, ''), 'UNK') as label,
    count(*)::bigint as clicks
  from public.logs l
  group by label
  order by clicks desc, label asc
  limit greatest(coalesce(p_limit, 10), 1);
$$;

revoke all on function public.resolve_redirect(text, text, integer, text, text, text, text, text) from public, anon, authenticated;
grant execute on function public.resolve_redirect(text, text, integer, text, text, text, text, text) to service_role;

revoke all on function public.stats_total_clicks() from public, anon, authenticated;
grant execute on function public.stats_total_clicks() to service_role;

revoke all on function public.stats_clicks_by_slug(integer) from public, anon, authenticated;
grant execute on function public.stats_clicks_by_slug(integer) to service_role;

revoke all on function public.stats_daily(integer) from public, anon, authenticated;
grant execute on function public.stats_daily(integer) to service_role;

revoke all on function public.stats_hourly(integer) from public, anon, authenticated;
grant execute on function public.stats_hourly(integer) to service_role;

revoke all on function public.stats_top_referrers(integer) from public, anon, authenticated;
grant execute on function public.stats_top_referrers(integer) to service_role;

revoke all on function public.stats_top_devices(integer) from public, anon, authenticated;
grant execute on function public.stats_top_devices(integer) to service_role;

revoke all on function public.stats_top_countries(integer) from public, anon, authenticated;
grant execute on function public.stats_top_countries(integer) to service_role;

insert into public.redirect_rules (
  slug,
  target_url,
  status_code,
  is_active,
  pixel_enabled,
  pixel_type,
  pixel_config
)
values
  (
    'promo',
    'https://example.com/promo?src=redirect',
    302,
    true,
    true,
    'meta',
    '{"id":"META_PIXEL_ID","token":"META_ACCESS_TOKEN","event_name":"PageView","custom_params":{"campaign":"spring"}}'::jsonb
  ),
  (
    'docs',
    'https://example.com/docs',
    301,
    true,
    false,
    null,
    null
  ),
  (
    'partner',
    'https://partner.example.com/offer',
    302,
    true,
    true,
    'postback',
    '{"id":"https://webhook.site/your-endpoint","token":"","event_name":"click","custom_params":{"source":"redirector"}}'::jsonb
  )
on conflict (slug) do nothing;
